version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbitleap-solo-miner_dashboard_1
      APP_PORT: 8000

  dashboard:
    image: ghcr.io/qbitleap/qbitleap-backend:0.1.1
    restart: on-failure
    depends_on:
      - qbitd
    environment:
      QBIT_RPC_HOST: qbitd
      QBIT_RPC_PORT: 8352
      QBIT_RPC_USER: qbitleap
      QBIT_RPC_PASSWORD: qbitleap-change-me

  qbitd:
    image: ghcr.io/qbitleap/qbitleap-qbit-core:0.1.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/qbit:/data
    command:
      - -datadir=/data
      - -server=1
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=qbitleap
      - -rpcpassword=qbitleap-change-me
      - -printtoconsole
